#+LATEX_HEADER: \input{../lit-header}
#+TITLE: Selection
#+OPTIONS: ^:{}
:NOTE:
Going back to editing the rust code, directly, until I can get
this org mode interface a bit smoother.
:END:

* Bring dependencies into scope
#+NAME: bring dependencies into scope
#+BEGIN_SRC rust :tangle selector.rs :noweb tangle
  extern crate rand; 

  use std::thread::{spawn, JoinHandle};
  use std::sync::mpsc::{sync_channel, Receiver, SyncSender};
  use std::cell::RefCell;
  use std::sync::{Arc,RwLock}; 
  use std::collections::VecDeque;

  use self::rand::{Rng, SeedableRng};
  use self::rand::isaac::Isaac64Rng;

  use par::statics::*;
  use gen::genotype::*;
  use gen::phenotype::{FitFuncs,Creature,Fitness,FitnessOps,Phenome};
  use evo::crossover::{homologous_crossover};
  use fit::circbuf::{CircBuf};
#+END_SRC

* Selection on a Stream

One of the interesting design decisions that crystallized in engineering
this iteration of ROPER has been to treat the population as a cyclical
"stream", rather than as a mutable collection. 

The stream originates in with the seeder, proceeds through the hatchery,
on to the evaluator, and then to the selection and breeding actors, without
any need to synchronize a mutable population vector. What makes this feasible
is the way that Rust handles the ~Send~ trait: all that's transferred when a
~Creature~ is sent across a channel is the deed for ownership. This operation
is no slower than indexing into a vector, practically speaking. 

The only real speedbump lies with the selection actor. Sticking with tournament
selection for the time being, we want to retain some capacity to select the
combatants in a tournament /at random/. But randomly selecting from a stream
seems to require first collecting the incoming elements into a buffer. 

So, let there be a buffer. The selector will wait until ~n~ creatures have
arrived through the channel, and then perform tournament selection on that
buffer. Some number ~tsize~ of those creatures will be chosen for a tournament
-- perhaps several tournaments, in parallel. It will /take/ ~tsize~ creatures, 
on a secondary channel, then return ~tsize~ back, but of those ~tsize~, ~tsize/2~
will be the winners of the tournament, and ~tsize/2~ will be newborns.


** TODO Redesign this module

Basically, we have two paths we can take, here: either commit to the stateful approach, and
encase the creatures in RefCells /from the beginning/, so that we can mutate them in-place
-- an approach that is only weakly motivated by the current set up, since the selection window
is essentially ephemeral -- or, instead, commit to the functional and stream-oriented approach
we've taken elsewhere, and make the breeder functional. The tournament, e.g., doesn't /need/ to
mutate the window in-place. It can, instead, just return new creatures, transfer ownership of 
them on doing so, and then inject them back into the stream. 


** Spawning the selector/breeder

As creatures enter the breeding thread, through the =into_breeder_tx=
channel, they are assigned to a randomly chosen slot in the =arena=. 
When a second creature is assigned to the same slot -- when there is
a collision -- a tournament is triggered. The loser is destroyed, and
the winner is moved to a mating pool. 

When the mating pool has reached a certain capacity, its residents will
pair off according to compatibility. Each creature will pair with the
creature in the pool with whom it is most compatible. (We could introduce
some degree of noise into this selection as well.) 

The mating pairs then reproduce through homologous crossover, and then
both the parents and the offspring are returned to the population stream.

The arena needs:
- a channel to recv creatures from the breeder thread
- a channel to send creatures to the mating thread
- a channel to recv creatures from the mating thread
- a channel to send creatures back to the breeder thread
  (or to the next phase in the evolution stream)
 
We can probably reuse the pattern that we've already used in
the hatchery and elsewhere. 


#+NAME: spawn the arena
#+BEGIN_SRC rust :tangle selector.rs :noweb tangle
#+END_SRC

#+NAME: spawn the selector 
#+BEGIN_SRC rust :tangle selector.rs :noweb tangle
  pub fn spawn_breeder(
      window_size: usize,
      hatch_tx: &SyncSender<Creature>,
  ) -> (SyncSender<Creature>, Receiver<Creature>, JoinHandle<()>) {
      let hatch_tx = hatch_tx.clone();
      let (from_breeder_tx, from_breeder_rx) = sync_channel(*CHANNEL_SIZE);
      let (into_breeder_tx, into_breeder_rx) = sync_channel(*CHANNEL_SIZE);
      let mut rng_seed = RNG_SEED.clone();
      let sel_handle = spawn(move || {
          /* TODO */
          let mut sel_window: Vec<Creature> = Vec::with_capacity(window_size);
          for incoming in into_breeder_rx {
              /* STUB, because the spice must flow */
              let incoming : Creature = incoming;
              //if incoming.generation() > 1 {
              //    println!("[!] Gen {} incoming!\n{}", incoming.generation(), incoming);
              //}
              sel_window.push(incoming);
              if sel_window.len() >= window_size {
                  // causing SendError on eval/log,breed //
                  let mut offspring = tournament(&mut sel_window, rng_seed);
                  while sel_window.len() > 0 {
                      match sel_window.pop() {
                          Some(outgoing) => {
                              match from_breeder_tx.send(outgoing) {
                                  Ok(_) => (),
                                  Err(e) => println!("Error sending to from_breeder_tx: {:?}", e),
                              }
                          },
                          None => panic!("unreachable?"),
                      }
                  }
                  while offspring.len() > 0 {
                      match offspring.pop() {
                          Some(outgoing) => {
                              match hatch_tx.send(outgoing) {
                                  Ok (_) => (),
                                  Err(e) => println!("Error sending to hatch_tx: {:?}",e),
                              }
                          },
                          None => panic!("unreachable??"),
                      }
                  }
              }
          }
      });
    
      (into_breeder_tx, from_breeder_rx, sel_handle)
  }
#+END_SRC

** Selection functions

To work with the form of homologous crossover implemented in the
~emu::crossover~ module, we may wish to use simple mate selection
algorithm, which increases the likelihood that mating pairs will
have "compatible" crossover masks. But this is a probabilistically
delicate operation. We don't want to create a perverse incentive
that will incline the population towards crossover masks that consist
entirely of ~1~ bits (and so which are /maximally compatible/ with other
masks), simply for the sake of increasing their likelihood of being
chosen for tournaments. 

On the other hand, this incentive will only turn out to be "perverse"
if it overwhelms the selective pressure (which we have theoretically
grounded reasons to expect) for sparse crossover masks. It could turn
out to be a useful, countervailing pressure that inclines the masks
to be as dense as possible, without losing the benefits of sparseness.
(The benefit of a sparse crossover mask, of course, is that it reduces
the probability of destructive crossover.)

#+NAME: measure crossover mask compatibility
#+BEGIN_SRC rust :tangle selector.rs :noweb tangle

    fn xover_compat(c1: u64, c2: u64) -> usize {
        (c1 & c2).count_ones() as usize
    }
  /* FOOBAR */
#+END_SRC

The static variable ~MATE_SELECTION_FACTOR~ will be used...

#+NAME: perform selection and mating
#+BEGIN_SRC rust :tangle selector.rs :noweb tangle

  fn tournament(selection_window: &mut Vec<Creature>,
                seed: RngSeed) -> Vec<Creature> {
      let mut rng = Isaac64Rng::from_seed(seed);
      /* note: seed creation should probably be its own utility function */
      let mut new_seed: [u8; 32] = [0; 32];
      for i in 0..32 { new_seed[i] = rng.gen::<u8>() }


      if (*TSIZE as f32 * *MATE_SELECTION_FACTOR > selection_window.len() as f32) {
          println!("TSIZE = {}; MATE_SELECTION_FACTOR = {}; selection_window.len() = {}",
                   ,*TSIZE, *MATE_SELECTION_FACTOR, selection_window.len());
          panic!("aarggh");
      };
      let mut indices = rand::seq::sample_indices(&mut rng,
                                                  selection_window.len(),
                                                  (*TSIZE as f32 * *MATE_SELECTION_FACTOR)
                                                  .floor() as usize);
      /* TODO: take n times as many combatants as needed, then winnow
       ,* out those least compatible with first combatant's crossover mask
       ,*/
      let x1 = selection_window[0].genome.xbits;
      let xbit_vec : Vec<u64> = selection_window.iter().map(|c| c.genome.xbits).collect();
      let compatkey = |i: &usize| {
          let x2 = xbit_vec[*i];

          64 - xover_compat(x1, x2)
      };

    // comment to simply disable compatibility sorting
      indices.sort_by_key(compatkey);
      /* now drop the least compatible from consideration */
      indices.truncate(*TSIZE);

      {
          let fitkey = |i: &usize| {
              let i = *i;
              let result = 
                  (&selection_window)[i]
                  .fitness
                  .as_ref()
                  .unwrap() /* FIXME bluff for debugging */
                  .mean();
              (result * 10000.00) as usize
          };
          /* now, sort the remaining indices by the fitness of their creatures */
          /* TODO -- we need a pareto sorting function */
          indices.sort_by_key(fitkey);
          indices.reverse();
      }
      /* TODO: Pareto ranking */
      /*
      Instead of /sorting/ the indices, filter or partition them according to
      pareto dominance. The filter function would look like this:

      (Naive implementation -- needs to be optimized, since it looks quadratic)
       ,*/
      let mut pareto_front : Vec<usize>;
      { /* block to contain immutable borrow of the window */
           let pareto_filter = | index: &&usize | {
               let fvec = &selection_window[**index].fitness.as_ref().unwrap();
               /* fvec is dominated if there exists another fitness vector
               fvec2 in selection_window such that fvec2[i] > fvec[i] for
               all i under fvec.len() */
               let len = fvec.len();
               let num_dominators = indices.iter()
                   .filter(| i | {
                       if i == index { return false };
                       let c = &selection_window[**i];
                       let fvec_d = c.fitness.as_ref().unwrap();
                       let mut result = true;
                       for i in 0..len {
                           if result == false { break };
                           if fvec[i] >= fvec_d[i] {
                             //  println!("[PARETO]=[{}]=> {:?} >= {:?}", index, fvec[i], fvec_d[i]);
                               result = false;
                           } else {
                               //println!("[PARETO]=[{}]=> {:?} <  {:?}", index, fvec[i], fvec_d[i]);
                           }
                       }
                       if result {
                           //println!("[PARETO]=[{}]=> fvec {:?} is DOMINATED by fvec_d {:?}", index, fvec, fvec_d);
                       } else {
                          // println!("[PARETO]=[{}]=> fvec {:?} is not dominated by fvec_d {:?}", index, fvec, fvec_d);
                       }
                       result
                   })
                   .count();
               //println!("[PARETO] num_dominators of {:?} == {}", fvec, num_dominators);
               num_dominators == 0 /* return true only for the pareto front */
           };
           pareto_front = indices.iter()
           .filter(pareto_filter)
           .map(|n| *n)
           .collect::<Vec<usize>>();
  /*
           let for_show = indices.iter() .map(|i| ((selection_window[*i]).fitness.as_ref().unwrap().clone())) .collect::<Vec<Vec<usize>>>();
           println!("[PARETO] pareto_filter results: {:?}",
                    indices.iter().map(|i| (*i, pareto_filter(&i))).collect::<Vec<(usize,bool)>>());
           println!("[PARETO] fvecs: {:?}", for_show);
           println!("[PARETO] indices = {:?}", indices);
           println!("[PARETO] Front: {:?}", pareto_front);
  ,*/
           rng.shuffle(&mut pareto_front);
      }
      /*

      ,*/
      /* and choose the parents and the fallen */
      // *TSIZE must be >= 4.
      /* The dead */
      /* The parents */
      assert!(pareto_front.len() >= 1);
      let (p0, p1) : (usize, usize);
      p0 = pareto_front[0];
      if pareto_front.len() >= 2 {
          p1 = pareto_front[1];
      } else {
          p1 = indices[0];
      }
      //let (d0, d1) = (indices[*TSIZE-1], indices[*TSIZE-2]);
      /* Consider filtering against the pareto front instead of the parent pair */
      let mut dead_meta_idx = *TSIZE-1;
      assert!(*TSIZE > 2);
      while indices[dead_meta_idx] == p0 || indices[dead_meta_idx] == p1 {
          dead_meta_idx -= 1;
          assert!(dead_meta_idx >= 0);
      }
      let d0 = indices[dead_meta_idx];
      dead_meta_idx -= 1;
      while indices[dead_meta_idx] == p0 || indices[dead_meta_idx] == p1 {
          dead_meta_idx -= 1;
          assert!(dead_meta_idx >= 0);
      }
      let d1 = indices[dead_meta_idx];

      assert!(p0 != d0);
      assert!(p0 != d1);
      assert!(p1 != d0);
      assert!(p1 != d1);
      //let (p0, p1) = (indices[0], indices[1]);




   /* I think I need to have the selection window consist of refcells of creatures, 
      instead of just naked creatures */ /* FIXME */ 
      let mut offspring;
      {
          let mother = &selection_window[p0];
          let father = &selection_window[p1];
          //let dead0  = &selection_window[d0];
          //let dead1  = &selection_window[d1];
          //println!("** mother.fitness = {:?}; father.fitness = {:?}; dead0.fitness = {:?}; dead1.fitness = {:?}",
          //         mother.fitness, father.fitness, dead0.fitness, dead1.fitness);
          offspring = homologous_crossover(mother, father, &mut rng);
          offspring[0].inherit_problems(&father);
          offspring[1].inherit_problems(&father);
      }
      /* now, place the offspring back in the population by inserting them
       ,* into the selection window
       ,*/
      //selection_window[d0] = offspring.pop().unwrap();
      //selection_window[d1] = offspring.pop().unwrap();
      /* It's essential that we remove the higher index first */
      assert!(d0 != d1);
      let first_to_kill = usize::max(d0, d1);
      let next_to_kill = usize::min(d0, d1);
      selection_window.swap_remove(first_to_kill);
      selection_window.swap_remove(next_to_kill);
      offspring
  }
#+END_SRC

* TODO implement a carousel mechanism in the selector

I think the selector component might be a bit of a bottleneck right now. 
Implement a carousel, like you did for the evaluator and the hatchery. 
This will help balance the load. 
